--- 
- name: This playbook is part of r1cloud challange it sets network bonding for recent Ubuntu releases
  hosts: "{{Target_Host}}"
  vars_files: vars.yaml
  tasks: 
       - package_facts:
           manager: "auto"
       - name: Changing grub to set traditional interface naming convention.
         lineinfile:
            name: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX='
            line: GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
         when: not 'eth0' in  ansible_interfaces
         notify:
           - update_grub
           - fix_eth0    
           - system_reboot   
       - name: Force to run the previous handlers 
         meta: flush_handlers          
       - name: Changing netplan to traditional networking service ifupdown
         package:
            name: ifupdown
            state: latest
         when: not 'ifupdown' in ansible_facts.packages   
         notify:
           - system_reboot
       - setup:     
       - name: Showing eth* interface devices for debuging purpose 
         set_fact:
            if_list: "{{ansible_interfaces | reject('match','lo') |reject('match','bond0') | select('string') | sort | list }}"
       - debug:
            msg: The following devices are going to aggregate {{item}}
         loop: "{{ if_list }}"


       - name: Installing ifenslave-2.6 package
         package:
            name: ifenslave
            state: latest
         when: not 'ifenslave' in ansible_facts.packages
       - name: Create a directory inside /etc/network/interfaces
         file:
            name: /etc/network/interfaces.d
            state: directory

       - name: Enabling kernel module
         command:
           cmd: modprobe bonding
       - name: Source interface.d 
         template:
           src: if_source.j2
           dest: /etc/network/interfaces
       - name: Set network bonding
         template:
           src: r1netbond.j2
           dest: /etc/network/interfaces.d/bond
         notify:
          - system_reboot
  handlers:
           - name: update_grub
             command:
                cmd: update-grub
           - name: fix_eth0
             template:
                src: fix_eth0.j2
                dest: /etc/network/interfaces
           - name: system_reboot
             reboot:        
          
          

